self.subsys3_clk             = Input(UInt(1))
single_assign(self.subsys3_clk, self.u_subsys3.clk)
self.subsys3_rst_n             = Input(UInt(1))
single_assign(self.subsys3_rst_n, self.u_subsys3.rst_n)
self.subsys3_data_conf     =        Input(UInt(32))
single_assign(self.subsys3_data_conf, self.u_subsys3.data_conf)
self.subsys3_data_valid             = Input(UInt(1))
single_assign(self.subsys3_data_valid, self.u_subsys3.data_valid)
self.subsys3_data_v     =        Input(UInt(8))
single_assign(self.subsys3_data_v, self.u_subsys3.data_v)
self.subsys3_rdatahs_1     =        Input(UInt(8))
single_assign(self.subsys3_rdatahs_1, self.u_subsys3.rdatahs_1)
self.subsys3_stopstatedata_0             = Input(UInt(1))
single_assign(self.subsys3_stopstatedata_0, self.u_subsys3.stopstatedata_0)
single_assign(self.u_subsys3.subsys2_to_subsys3_ting, self.u_subsys2.subsys2_to_subsys3_ting)
single_assign(self.u_subsys3.subsys2_to_subsys3_d, self.u_subsys2.subsys2_to_subsys3_d)
single_assign(self.u_subsys3.subsys3_tie_constant, UInt(9,0x7))
