//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:6920291faae44e065da9d22d9610fc31]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: bf4db5e6ad7ff4807cbfb265464b155a
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:6920291faae44e065da9d22d9610fc31]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:1f842ed83242fc2f03017c54ae880e26]
//Written by UHDL in 2023-07-05 15:36:21
//[UHDL]Tool Message End [md5:1f842ed83242fc2f03017c54ae880e26]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:bf4db5e6ad7ff4807cbfb265464b155a]
module axi_slave_WIDTH_32_ADDRWD_16 (
	input         D_u_slv_vld_s ,
	output        D_u_slv_rdy_s ,
	input  [31:0] D_u_slv_data_s,
	input  [15:0] D_u_slv_addr_s,
	input         D_u_slv_clk   ,
	input         D_u_slv_rst_n );
	wire        u_slv_clk   ;
	wire        u_slv_rst_n ;
	wire        u_slv_vld_s ;
	wire        u_slv_rdy_s ;
	wire [31:0] u_slv_data_s;
	wire [15:0] u_slv_addr_s;
	assign D_u_slv_rdy_s = u_slv_rdy_s;
	
	assign u_slv_clk = D_u_slv_clk;
	
	assign u_slv_rst_n = D_u_slv_rst_n;
	
	assign u_slv_vld_s = D_u_slv_vld_s;
	
	assign u_slv_data_s = D_u_slv_data_s;
	
	assign u_slv_addr_s = D_u_slv_addr_s;
	
	axi_slave #(
		.WIDTH(32),
		.ADDRWD(16))
	u_slv (
		.clk(u_slv_clk),
		.rst_n(u_slv_rst_n),
		.vld_s(u_slv_vld_s),
		.rdy_s(u_slv_rdy_s),
		.data_s(u_slv_data_s),
		.addr_s(u_slv_addr_s));

endmodule
//[UHDL]Content End [md5:bf4db5e6ad7ff4807cbfb265464b155a]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

